# Generated by Django 4.2 on 2024-01-27 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, default='default_post_pic.jpg', upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin_allowed', models.CharField(choices=[('allowed', 'ALLOWED'), ('not_allowed', 'NOT_ALLOWED')], default='not_allowed', max_length=11)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
