# Generated by Django 4.2 on 2024-01-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='admin_allowed',
            field=models.CharField(choices=[('allowed', 'ALLOWED'), ('not_allowed', 'NOT_ALLOWED')], default='not_allowed', max_length=11),
        ),
    ]
