# Generated by Django 4.2 on 2024-01-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='block',
            field=models.CharField(choices=[('blocked', 'BLOCKED'), ('unblocked', 'UNBLOCKED')], default='unblocked', max_length=9),
        ),
    ]
