# Generated by Django 4.2 on 2024-01-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
